### ISSUE TITLE
Encoding.UTF8.GetBytes(eltKey) will System.ArgumentNullException when eltKey is null.

### ISSUE THREAD

**Issue by AWaterColorPen** [tg123/ConsistentSharp#1]
ConsistentSharp.cs line 205, 
`    return Crc32.Hash(Encoding.UTF8.GetBytes(eltKey));`
`Encoding.UTF8.GetBytes(eltKey)` will throw System.ArgumentNullException, if `eltKey `is null.

**Comment by tg123** [comment]
fix a22642083fb910cb27f66167100fb657dd58e7f4
